package ImagePane;

import javafx.scene.image.Image;

public class AllImage {
    public static Image Image_Self_Flighter=new Image       ("Image\\Flighter.png");
    public static Image Image_Self_Basic_Bullet=new Image   ("Image\\Basic_Bullet.png");
    public static Image Image_Self_Super_Bullet=new Image   ("Image\\Super_Bullet.png");
    public static Image Image_Background_1=new Image        ("Image\\Background_1.png");
    public static Image Image_Enemy_Basic_Bullet=new Image  ("Image\\Enemy_Basic_Bullet.png");
    public static Image Image_Enemy_Flighter_Type1=new Image("Image\\Enemy_1.png");
    public static Image Image_Enemy_Flighter_Type2=new Image("Image\\Enemy_2.png");
    public static Image Image_Enemy_Elite_1=new Image       ("Image\\Enemy_1.png");
    public static Image Image_Enemy_Elite_2=new Image       ("Image\\Enemy_1.png");
    public static Image Image_Enemy_Elite_Bullet_1=new Image("Image\\Enemy_Elite_Bullet_1.png");
    public static Image Image_Enemy_Elite_Bullet_2=new Image("Image\\Enemy_Elite_Bullet_2.png");
    public static Image Image_Boom1_1=new Image             ("Image\\Boom_1_1.png");
    public static Image Image_Boom1_2=new Image             ("Image\\Boom_1_2.png");
    public static Image Image_Boom1_3=new Image             ("Image\\Boom_1_3.png");
    public static Image Image_Boom1_4=new Image             ("Image\\Boom_1_4.png");
    public static Image Image_Boom1_5=new Image             ("Image\\Boom_1_5.png");
    public static Image Image_Boom1_6=new Image             ("Image\\Boom_1_6.png");
    public static Image Image_Super_Bullet_Update=new Image ("Image\\Super_Bullet_Update.png");
    public static Image Image_Health=new Image              ("Image\\Health.png");
    public static Image Image_Boss=new Image                ("Image\\Boss.png");
    public static Image Image_Left_Flighter=new Image       ("Image\\Flighter_Left.png");
    public static Image Image_Right_Flighter=new Image      ("Image\\Flighter_Right.png");
    public static Image Image_Boss_Bullet_1=new Image       ("Image\\Boss_Bullet_1.png");
    public static Image Image_G_1=new Image                 ("Image\\Boss_G_1.png");
    public static Image Image_G_2=new Image                 ("Image\\Boss_G_2.png");
    public static Image Image_G_3=new Image                 ("Image\\Boss_G_3.png");
    public static Image Image_G_4=new Image                 ("Image\\Boss_G_4.png");
    public static Image Image_Boss_Health=new Image         ("Image\\Boss_Health.png");
    public static Image Image_G_Warning=new Image           ("Image\\G_Warning.png");
    public static Image Image_Boss_Warning=new Image        ("Image\\Boss_Warning.png");
    public static Image Image_Title_Back=new Image          ("Image\\Title_Back.png");
    public static Image Image_Start=new Image               ("Image\\Start.png");
    public static Image Image_Start_Frame=new Image         ("Image\\Start_Frame.png");
    public static Image Image_Boom2_1=new Image             ("Image\\Boom_2_1.png");
    public static Image Image_Boom2_2=new Image             ("Image\\Boom_2_2.png");
    public static Image Image_Boom2_3=new Image             ("Image\\Boom_2_3.png");
    public static Image Image_Boom2_4=new Image             ("Image\\Boom_2_4.png");
    public static Image Image_Boom2_5=new Image             ("Image\\Boom_2_5.png");
    public static Image Image_Boom2_6=new Image             ("Image\\Boom_2_6.png");
    public static Image Image_Boom2_7=new Image             ("Image\\Boom_2_7.png");
    public static Image Image_Boom2_8=new Image             ("Image\\Boom_2_8.png");
    public static Image Image_Boom2_9=new Image             ("Image\\Boom_2_9.png");
    public static Image Image_Boom2_10=new Image            ("Image\\Boom_2_10.png");
    public static Image Image_Boom2_11=new Image            ("Image\\Boom_2_11.png");
    public static Image Image_Bullet_Boom=new Image         ("Image\\Boom_dwj.png");
    public static Image Image_Boss_daodan=new Image         ("Image\\Boss_Bullet_2.png");
}
